name: flutter_marvel_api
description: A MARVEL Rest API library
version: 0.0.1
homepage: https://github.com/NKlage/flutter_marvel_api

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  crypto: ^3.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http_mock_adapter: ^0.3.3

flutter:

