name: flutter_mcu_api
description: An MCU REST API library to easily access the Marvel API.
version: 0.1.1
repository: https://github.com/NKlage/flutter_mcu_api

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.1.1
  crypto: ^3.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http_mock_adapter: ^0.4.2

flutter:

